package org.eidos.reader.ui.misc.values

val LANGUAGES = mapOf(
        "" to "",
        "af Soomaali" to "so",
        "Afrikaans" to "afr",
        "العربية" to "ar",
        "ܐܪܡܝܐ | ארמיא" to "arc",
        "հայերեն" to "hy",
        "Bahasa Indonesia" to "id",
        "Bahasa Malaysia" to "ms",
        "Български" to "bg",
        "বাংলা" to "bn",
        "Basa Jawa" to "jv",
        "беларуская" to "be",
        "Bosanski" to "bos",
        "brezhoneg" to "br",
        "Català" to "ca",
        "Čeština" to "cs",
        "Chinuk Wawa" to "chn",
        "Cymraeg" to "cy",
        "Dansk" to "da",
        "Deutsch" to "de",
        "eesti keel" to "et",
        "Ελληνικά" to "el",
        "English" to "en",
        "Español" to "es",
        "Esperan" to "eo",
        "Euskara" to "eu",
        "فارسی" to "fa",
        "Filipino" to "fil",
        "Français" to "fr",
        "Furlan" to "fur",
        "Gaeilge" to "ga",
        "Gàidhlig" to "gd",
        "Galego" to "gl",
        "𐌲𐌿𐍄𐌹𐍃𐌺𐌰" to "got",
        "中文-客家话" to "hak",
        "한국어" to "ko",
        "Hausa | هَرْشَن هَوْسَ" to "hau",
        "हिन्दी" to "hi",
        "Hrvatski" to "hr",
        "Interlingua" to "ia",
        "isiZulu" to "zu",
        "Íslenska" to "is",
        "Italiano" to "it",
        "עברית" to "he",
        "ქართული" to "kat",
        "Khuzdul" to "qkz",
        "Кыргызча" to "kir",
        "Kiswahili" to "sw",
        "kreyòl ayisyen" to "ht",
        "Langue des signes québécoise" to "fcs",
        "Latviešu valoda" to "lv",
        "Lëtzebuergesch" to "lb",
        "Lietuvių kalba" to "lt",
        "Lingua latina" to "la",
        "Magyar" to "hu",
        "македонски" to "mk",
        "മലയാളം" to "ml",
        "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ" to "mnc",
        "मराठी" to "mr",
        "ᠮᠣᠩᠭᠣᠯ ᠪᠢᠴᠢᠭ᠌ | Монгол Кирилл үсэг" to "mon",
        "မြန်မာဘာသာ" to "my",
        "中文-闽南话 臺語" to "nan",
        "Nederlands" to "nl",
        "日本語" to "ja",
        "Norsk" to "no",
        "پښتو" to "ps",
        "Plattdüütsch" to "nds",
        "Polski" to "pl",
        "Português brasileiro" to "ptBR",
        "Português europeu" to "ptPT",
        "ਪੰਜਾਬੀ" to "pa",
        "Quenya" to "qya",
        "Română" to "ro",
        "Русский" to "ru",
        "Scots" to "sco",
        "Shqip" to "sq",
        "Sindarin" to "sjn",
        "සිංහල" to "si",
        "Slovenčina" to "sk",
        "Slovenščina" to "slv",
        "Sprēkō Þiudiskō" to "gem",
        "српски" to "sr",
        "Suomi" to "fi",
        "Svenska" to "sv",
        "தமிழ்" to "ta",
        "ไทย" to "th",
        "Thermian" to "tqx",
        "བོད་སྐད་" to "bod",
        "Tiếng Việt" to "vi",
        "tlhIngan-Hol" to "tlh",
        "ki Pona" to "qtp",
        "Türkçe" to "tr",
        "Українська" to "uk",
        "ئۇيغۇر تىلى" to "uig",
        "中文-吴语" to "wuu",
        "יידיש" to "yi",
        "中文-广东话 粵語" to "yue",
        "中文-普通话 國語" to  "zh"
)
